server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: ${USER_DB_URL:jdbc:postgresql://localhost:5432/ecommerce_users}
    username: ${USER_DB_USERNAME:postgres}
    password: ${USER_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

spring.cloud.openfeign.circuitbreaker.enabled: true

resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

jwt:
  secret: ${JWT_SECRET:change-this-secret-in-production-change-this-secret-in-production}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}
