server:
  port: 8083
spring:
  application:
    name: cart-service
  datasource:
    url: ${CART_DB_URL:jdbc:postgresql://localhost:5432/ecommerce_carts}
    username: ${CART_DB_USERNAME:postgres}
    password: ${CART_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
resilience4j.circuitbreaker.instances.default:
  sliding-window-size: 10
  failure-rate-threshold: 50
  wait-duration-in-open-state: 10s
